services:
  database:
    image: postgres:15
    container_name: prewave_edge_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prewave
      POSTGRES_PASSWORD: prew4vePwd
      POSTGRES_DB: tree_edge_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  app:
    image: gradle:8.13-jdk17-alpine
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./build/libs/:/app
    command: sh -c "java -jar prewave-assignment-0.0.1-SNAPSHOT.jar"

    container_name: prewave-assignment
    environment:
      SERVER_PORT: 8080
      SERVER_ADDRESS: 0.0.0.0
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: prewave
      DB_PASSWORD: prew4vePwd
      DB_NAME: tree_edge_db
    depends_on:
      - database

volumes:
  db-data:
