version: '3.8'

services:
  database:
    image: postgres:15
    container_name: prewave_edge_database
    environment:
      POSTGRES_USER: prewave
      POSTGRES_PASSWORD: prew4vePwd
      POSTGRES_DB: tree_edge_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prewave-assignment
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: prewave
      DB_PASSWORD: prew4vePwd
      DB_NAME: tree_edge_db
    ports:
      - "19305:19305"
    depends_on:
      - database

volumes:
  db-data:
