spring:
  datasource:
    url: jdbc:postgresql://database:5432/tree_edge_db
    username: prewave
    password: prew4vePwd
    driver-class-name: org.postgresql.Driver
server:
  address: 0.0.0.0
  port: 8080
